// import "../styles/globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import type { AppProps } from "next/app";
import Head from "next/head";
import Layout from "../components/Layout";
import { AuthContextProvider } from "../context/AuthContext";
import { FavoriteContextProvider } from "../context/favoriteContext";
import { ThemeColorContextProvider } from "../context/ColorContext";
export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <FavoriteContextProvider>
        <AuthContextProvider>
          <ThemeColorContextProvider>
            <Head>
              <title>The Healing Museum</title>
              {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <ChakraProvider>
              <Layout>
                <Component {...pageProps} />
              </Layout>
            </ChakraProvider>
          </ThemeColorContextProvider>
        </AuthContextProvider>
      </FavoriteContextProvider>
    </>
  );
}
